language: scala
scala:
- 2.11.7
- 2.12.0-M2
git:
  depth: 1
cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2
  - $HOME/.sbt

env:
  global:
  - secure: EiIU/od4+xs+UYNI+an212eR9P4aks1wp6fd3f1xRW5D/KCTDHcXRnpHsiiZM3+A9klVqTODdV1RDThUo8wcSro4IGjbTY3TniRjzYJnLOyuZFIGJWwN++lnepn/DwFk3Ckr661BcdIS0+5TybOD4ZzkcUOreU/0q/1qd4uqTRU=
  - secure: DNSLyto/JVJTLMsBxrxK0C0B1/bdHZrDmKxr2ZTgEE6HFTZOLnAB39MD3RS6rnPotZcffdwraBTjYwH21Z8G0byquDyYR0khKdACsW77vy9ZBkNa6YUwlrUov9t2TfdU83QFvjoe8TCBmNqiQqkgB62YO7XS1wIe+pXeFbAqe/U=

script:
- "[[ $TRAVIS_BRANCH == \"master\" ]] && export CMDS=\"test publish\" || export CMDS=\"test\""
- "echo \"Commands = $CMDS\""
- sbt ++$TRAVIS_SCALA_VERSION 'set javaOptions += "-Djunit.parallel.threads=2"' $CMDS
